package Communication;

public enum Operations {
    LOGIN,
    REGISTER,
    VERIFY_USER_EXISTS,
    FETCH_USER,
    UPLOAD_VIDEO,
    FETCH_ALL_VIDEOS,
    FETCH_PEER_IPS,
    SAVE_VIDEO_METADATA,
    DELETE_VIDEO_METADATA,
    UPDATE_VIDEO_METADATA,
    SAVE_THUMBNAIL,
    FETCH_ALL_THUMBNAILS,
    NUMBER_OF_ONLINE_PEERS,
    GET_VIDEO_METADATA

}
